services:
  postgresql:
    env_file: .env
    image: postgres:latest
    environment: 
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "${DATABASE_PORT}:5432"
  redis:
    image: redis/redis-stack-server
    env_file: .env
    container_name: "redis"
    ports:
      - "6379:6379"
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD} --user ${REDIS_USERNAME} on >${REDIS_PASSWORD} ~* allcommands --user default off nopass nocommands"
  selenium-hub:
    image: selenium/hub:4.7.2
    expose:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 5

  chrome:
    image: selenium/node-chrome:4.7.2
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  fastapi:
    env_file: .env
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment: 
      DATABASE_DRIVER_NAME: "postgresql+asyncpg"
      DATABASE_HOST: postgresql
      REDIS_OM_URL: "redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@redis:6379/0"
      SELENIUM_HUB_URL: "http://selenium-hub:4444/wd/hub"
      TZ: "Asia/Yekaterinburg"
    depends_on:
      - postgresql
      - redis
      - chrome
      - selenium-hub