services:
  postgresql:
    env_file: .env
    image: postgres:latest
    environment: 
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "${DATABASE_PORT}:5432"
  redis:
    image: redis/redis-stack-server
    env_file: .env
    container_name: "redis"
    ports:
      - "6379:6379"
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD} --user ${REDIS_USERNAME} on >${REDIS_PASSWORD} ~* allcommands --user default off nopass nocommands"
  selenium:
    image: selenium/standalone-chrome
    expose:
      - "4444"
  selenium-proxy:
    build:
      context: ./selenium-proxy
      dockerfile: Dockerfile
      args:
        SELENIUM_HUB_PASSWORD: $SELENIUM_HUB_PASSWORD
    depends_on:
      - selenium
    ports:
      - "4545:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  fastapi:
    env_file: .env
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment: 
      DATABASE_DRIVER_NAME: "postgresql+asyncpg"
      DATABASE_HOST: postgresql
      REDIS_OM_URL: "redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@redis:6379/0"
      SELENIUM_HUB_URL: "http://selenium:${SELENIUM_HUB_PASSWORD}@localhost:4545/wd/hub"
    depends_on:
      - postgresql
      - redis
      - selenium-proxy
