services:
  postgresql:
    env_file: .env
    image: postgres:latest
    environment: 
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "${DATABASE_PORT}:5432"
  redis:
    image: redis/redis-stack-server
    env_file: .env
    container_name: "redis"
    ports:
      - "6379:6379"
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD} --user ${REDIS_USERNAME} on >${REDIS_PASSWORD} ~* allcommands --user default off nopass nocommands"
  selenium:
    env_file: .env
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    environment:
      
  fastapi:
    env_file: .env
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment: 
      DATABASE_DRIVER_NAME: "postgresql+asyncpg"
      DATABASE_HOST: postgresql
      REDIS_OM_URL: "redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@redis:6379/0"
    depends_on:
      - postgresql
      - redis
