from src.application.dto.module import CreateModuleDTO


async def get_by_id(module_id: int): ...
async def get_all(page, limit, columns, sort, filter, desc): ...
async def create_module(dto: CreateModuleDTO): ...
async def delete(module_id: int): ...
