from .administrator import *
from .teacher import *
from .institute import *
from .module import *
from .subject import *
from .const_link import *
from .lesson import *
from .schedule import *
from .schedule_lessons import *
from .feedback import *
from .auth import *
from .user import *
from .extra_field import *
from .privelege import *
