from .administrator import Administrator
from .module import Module
from .feedback import Feedback
from .feedback_form import FeedbackForm
from .institute import Institute
from .lesson import Lesson
from .privileges import Privileges
from .schedule import Schedule
from .schedule_lesson import ScheduleLesson
from .study_group import StudyGroup
from .subject import Subject
from .teacher import Teacher
