from .administrator import Administrator
from .feedback import Feedback
from .feedback_form import FeedbackForm
from .institute import Institute
from .lesson import Lesson
from .privileges import Privileges
from .study_group import StudyGroup
from .subject import Subject
from .teacher import Teacher
from .teacher_subject import TeacherSubject
from .university import University
