from .administrator import Administrator
from .extra_field import ExtraField
from .extra_field_setting import ExtraFieldSetting
from .module import Module
from .feedback import Feedback
from .institute import Institute
from .lesson import Lesson
from .privilege import Privilege
from .schedule import Schedule
from .schedule_lesson import ScheduleLesson
from .study_group import StudyGroup
from .subject import Subject
from .teacher import Teacher
